### ISSUE TITLE
When you are setting the daily reminder the "save" button says "remind" - more confusing than helpful?

### ISSUE THREAD

**Issue by kursfjord** [freshteapot/learnalist-api#228]
That the save button says remind makes me think it will remind me instantly - which it doesn't. Maybe just opt for save?
![IMG_1326](https://user-images.githubusercontent.com/44695355/111755053-fa427d00-8898-11eb-8c01-269721217c22.PNG)

**Comment by freshteapot** [comment]
![image](https://user-images.githubusercontent.com/305673/166112712-6081ca5b-eb98-48a9-9318-abfe91b8b613.png)

@kursfjord slow response time! I ended up iterating a little, this is what is now live.

I will close the issue, but do open it of you think it needs more :)
